import './globals.css';

import type { Metadata } from 'next';

import Footer from '../components/layout/footer';
import Header from '../components/layout/header';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <main className="main">
          <Header />
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
